[tool.pytest.ini_options]
env = [
    "FRANKFURTER_URL=",
    "NB_RB_URL=",
    "NOTION_TOKEN=",
    "MEETINGS_DATABASE=",
    "BUDGET_BLOCK=",
    "BUDGET_PAGE=",
    "TO_DOS_BLOCK=",
    "BIRTHDAYS_BLOCK=",
    "BUDGET_DB=",
    "WEATHER_ROW=",
    "BROKER_BLOCK=",
    "PROFIT_BLOCK=",
    "INVESTMENT_PAGE=",
    "TRADERNET_PUBLIC_KEY=",
    "TRADERNET_PRIVATE_KEY="
]

[tool.coverage.report]
exclude_also = [
    'if __name__ == .__main__.:'
]
