name: Dashboard Update

on:
  workflow_dispatch:
    inputs:
      text_block:
        description: "Custom text to put in a Notion block"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notion-client

      - name: Mask input
        run: |
          echo "::add-mask::${{ github.event.inputs.text_block }}"

      - name: Update Dashboard
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          BLOCK_ID: ${{ secrets.BLOCK_ID }}
          CONTENT: ${{ github.event.inputs.text_block }}
        run: |
          python morning-dashboard.py
